# Generated by Django 4.2.6 on 2024-08-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
    ]
